name: labeled
description: A widget containing a label and a child widget
version: 0.0.1
homepage: https://github.com/brustolin/flutter-labeled

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
